import Head from "next/head";
import Image from "next/image";
import bg from '../assets/Frame.png';
import Logo from '../assets/Vectormtn.svg';
import Background from '../assets/login.svg'
import Yello from '../assets/Yello.svg';
import { BsEyeSlashFill } from 'react-icons/bs';
import { FaArrowRight } from 'react-icons/fa'
import Link from "next/link";



export default function Login() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="h-96 w-full relative">
                <Image src={Background} alt="background"
                    priority={true} unoptimized={true}
                    className="w-full h-screen object-cover absolute mix-blend-overlay " />
                {/* login form */}
                <div className="md:px-12 px-4 md:w-3/6">

                    {/* brand logo */}
                    <Link href="/home">
                        <Image src={Logo} alt="logo"
                            className="py-12 cursor-pointer" />
                    </Link>
                    <form className="bg-black/50 backdrop-blur-md md:w-4/6 w-full rounded-3xl
                    md:p-5 p-3">
                        <Image src={Yello} alt="yellow-text"
                            className="px-6 mt-8" />
                        <p className="text-xs text-[#999999] px-6">
                            Welcome back! please enter your details
                        </p>
                        {/* Email input */}
                        <div className="px-6 py-6">

                            <input type="email" className="border-[0.2px] transition duration-500 
                            placeholder-[#666] focus:placeholder-transparent border-[#ffffff1f] w-[280px] 
                                px-4 py-2 bg-[#212121] text-gray-50 rounded-md focus:outline-none"
                                placeholder="Email" />

                        </div>
                        {/* Password input */}
                        <div className="px-6 py-1">
                            <input type="password" className="border-[0.2px] transition duration-500 
                            placeholder-[#666] focus:placeholder-transparent border-[#ffffff1f] w-[280px] 
                                px-4 py-2 bg-[#212121] text-gray-50 rounded-md focus:outline-none"
                                placeholder="Password" />
                            <BsEyeSlashFill className="text-[#888888] relative bottom-7 left-64" />
                        </div>

                        <div className="mx-6 flex items-center space-x-7 bg-[#FFCB03] w-[170px] rounded-full mb-3">
                            <button className=" py-3 px-3 ">
                                Continue
                            </button>
                            <FaArrowRight className="flex items-center  justify-center 
                            text-xl h-5 w-5 p-1.5 text-white bg-black rounded-full" />
                        </div>
                    </form>
                </div>
            </main>
        </>
    )
}